cmd/ticommunitytars/main.go

Part of https://github.com/tidb-community-bots/ti-community-prow/issues/147

fix: refine external plugin config path

---

docs/src/SUMMARY.md
docs/src/workflows/label.md

Because I think maybe the label process cannot be a workflow.

chore: remove label workflow

---

docs/src/plugins/blunderbuss.md
internal/pkg/externalplugins/blunderbuss/blunderbuss.go
internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
internal/pkg/externalplugins/config.go
internal/pkg/externalplugins/config_test.go

The current solution is to only listen to labeled events, but there are still problems: 
If a PR only cancels the sig tag without reassigning a new sig tag, for example: if a PR mistakenly adds a sig tag, and then cancels the sig tag, at this time, there will be a problem of not revoking the review request.
close #144

feat: blunderbuss supports re-cc to reviewers when sig label added

---

web/.gitignore
web/.prettierignore
web/package-lock.json
web/package.json
web/pages/[org]/[repo]/pulls/[num]/owners.tsx
web/types/constant.ts

Because we support different owners URL in plugins(such as: community repo's lgtm use `ti-community-bot` as owners service), so the owners page also need to support it.

feat: support find owners endpoint

---

experiment/phony-rs/Cargo.toml
experiment/phony-rs/src/main.rs
experiment/phony-rs/static/index.html

- Make phony-rs async.
- Fewer dependencies and faster compilation.
update 2021-01-24:
- async sign payload
- `const SHA1_PREFIX: &str = "sha1=";` Note that the signature format should look like `sha1=7d38cdd689735b008b3c702edd92eea23791c5f6`

feat: async support for phony-rs

---

experiment/label-dumpling/Cargo.toml
experiment/label-dumpling/src/main.rs

fix:
```
thread 'main' panicked at 'not currently running on the Tokio runtime.', github.com-1ecc6299db9ec823/tokio-1.0.2/src/runtime/blocking/pool.rs:84:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It can run normally now.

fix: update dependencies to remove panic

---

docs/plugins/owners.md
internal/pkg/externalplugins/config.go
internal/pkg/externalplugins/owners/owners.go
internal/pkg/externalplugins/owners/owners_test.go

In order to support some repositories that don't have a sig, we need to add that feature.

feat: add use GitHub permission to owners

---

docs/plugins/blunderbuss.md
internal/pkg/externalplugins/blunderbuss/blunderbuss.go
internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go

Part of https://github.com/ti-community-infra/tichi/issues/315
Because we support multiple sigs and in practice we find that people assign revewers manually, we need to stop auto-assignment when there are manually assigned viewers. This feature is similar to not auto-assigning when we have /cc.

fix: only request reviewers when PR no requested reviewers

---

internal/pkg/externalplugins/config.go

close https://github.com/ti-community-infra/tichi/issues/231
I thought about it carefully and it actually makes sense to put the setting defaults in this position. Because they have to be set before the validate, and each plugin checks the file. So each plugin sets the defaults.

chore: remove TODO

---

internal/pkg/externalplugins/merge/merge.go
internal/pkg/externalplugins/merge/merge_test.go

cc: https://github.com/pingcap/tidb/pull/22860#issuecomment-787221552

fix: merge if the number of lgtm is greater than the required number

---

configs/prow-dev/config/plugins.yaml
internal/pkg/externalplugins/tars/tars.go

log look like:
{"event-GUID":"e70a40f6-7a56-11eb-9920-5b7df3cfafa3","event-type":"push","level":"info","msg":"Search for query \"archived:false is:pr is:open sort:created-asc org:\"ti-community-infra\" repo:\"test-dev\" base:\"/master\"\" cost 3 point(s). 4975 remaining.","plugin":"ti-community-tars","time":"2021-03-01T06:25:23Z"}
{"event-GUID":"e70a40f6-7a56-11eb-9920-5b7df3cfafa3","event-type":"push","level":"info","msg":"Considering 0 PRs.","plugin":"ti-community-tars","time":"2021-03-01T06:25:23Z"}
{"event-GUID":"e76c35b8-7a56-11eb-95cd-da45d7f2c8d6","event-type":"push","level":"info","msg":"Checking ti-community-infra/test-dev#/testaddeee PRs.","plugin":"ti-community-tars","time":"2021-03-01T06:25:23Z"}
{"event-GUID":"e76c35b8-7a56-11eb-95cd-da45d7f2c8d6","event-type":"push","level":" …

fix: refine tars query

---

internal/pkg/externalplugins/tars/tars.go
internal/pkg/externalplugins/tars/tars_test.go

When there is a PR conflict, the API call to update the PR does not report an error, so it causes the mechanism to update the PR after the push event to fail.

fix: check PR mergeable for tars

---

internal/pkg/externalplugins/tars/tars.go
internal/pkg/externalplugins/tars/tars_test.go

Tars failed again, with a large number of unknown states on the tidb repository. Then I took a closer look at the logs and found that the conflicting PRs actually report errors when they are updated. The reason we couldn't update other PRs was that tars also scanned for PRs without 'status/can-merge', and those PRs returned nil because they didn't have the label, and then the loop was terminated. So this time we don't check for mergeable and update the PRs directly. Even if we encounter conflicting PRs, the update will fail and we will end up with a PR that meets the requirements or all PRs do not meet the requirements.

fix: Tars no longer checks mergeable

---

internal/pkg/externalplugins/tars/tars.go
internal/pkg/externalplugins/tars/tars_test.go

Maybe fix https://github.com/ti-community-infra/tichi/issues/411
```release-note
Use MergeStateStatus to reduce the use of tars for the GitHub API.
```

fix: Use MergeStateStatus to reduce the use of tars for the GitHub API

---

internal/pkg/externalplugins/tars/tars.go

close https://github.com/ti-community-infra/tichi/issues/524
```release-note
tars wait a few seconds after receiving a comment.
```

fix: tars wait a few seconds after receiving a comment

---

.goreleaser.yml
cmd/rerere/main.go
deployments/components/rerere/Dockerfile
docs/README.md
docs/_sidebar.md
docs/components/rerere.md
internal/pkg/rerere/rerere.go
internal/pkg/rerere/rerere_test.go

Since the status of the tide can now be set to required, this may be an effective solution.

feat: revert rerere component

---

configs/prow-dev/config/external_plugins_config.yaml

It is difficult to review during testing, so we need to stop the blocker.

config(test-dev): stop block LGT labels

---

internal/pkg/rerere/rerere.go

Five minutes is too long. I think 1 minute is fine based on our current token usage.

fix(rerere): Check every minute

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
cmd/check-external-plugin-config/main.go
internal/pkg/externalplugins/config.go

The old version hasn't ARM architecture binary package for Mac (M1).

build: Bump golangci-lint from 1.31.0 to 1.41.1

---

configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml

Fix the problem that lifecycle commenter throw 422 error.
```
2021/07/16 07:24:12 main.go:213: Searching: org:ti-community-infra
-label:lifecycle/frozen
-label:lifecycle/stale
-label:lifecycle/rotten archived:false is:open updated:<=2021-04-17T07:24:12Z
time="2021-07-16T07:24:12Z" level=info msg="FindIssues(org:ti-community-infra\n-label:lifecycle/frozen\n-label:lifecycle/stale\n-label:lifecycle/rotten archived:false is:open updated:<=2021-04-17T07:24:12Z)" client=github
2021/07/16 07:24:12 main.go:194: Failed run: search failed: status code 422 not one of [200], body: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view …
```

fix: fix the commenter query format

---

internal/pkg/externalplugins/cherrypicker/cherrypicker.go
internal/pkg/externalplugins/label.go

close https://github.com/ti-community-infra/tichi/issues/539

feat: add label in case of conflict

---

internal/pkg/externalplugins/cherrypicker/cherrypicker.go
internal/pkg/externalplugins/label.go

fix: Revert "feat: add label in case of conflict (#652)"

---

cmd/ticommunitycherrypicker/main.go
internal/pkg/externalplugins/cherrypicker/cherrypicker.go
internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go

When a conflict occurs in the process of cherrypicker pick PR, a `fetch upstream` operation is required, which will cause errors to the private repository before.

fix(cherrypicker): fix failed to fetch private repo problem

---

internal/pkg/externalplugins/merge/merge.go
internal/pkg/externalplugins/merge/merge_test.go

If the commit hash is not found, check each commit.
A bad case: https://github.com/pingcap/ticdc/pull/2717

fix(merge): If the commit hash is not found, check each commit

---

internal/pkg/externalplugins/tars/tars.go
internal/pkg/externalplugins/tars/tars_test.go

fix: fix tars redundant merge base operation problem

---

.github/dependabot.yml

Daily update is too heavy for daily maintenance work, so it is modified to a weekly update.

config: make dependabot do update weekly

---

docs/en/plugins/format-checker.md
docs/plugins/format-checker.md
internal/pkg/externalplugins/config.go
internal/pkg/externalplugins/formatchecker/formatchecker.go
internal/pkg/externalplugins/formatchecker/formatchecker_test.go

close https://github.com/ti-community-infra/tichi/issues/768
- An option for each matching rule is provided. For example, contributors can skip the issue number check for some PRs that do not have to provide related issues by adding skip label. 
- When contributors labeled the skip label, pass the rule
- When contributors unlabeled the skip label, recheck the rule
- When contributors labeled / unlabeled the other label, do not trigger the check

feat: format checker support skip label option

---

docs/en/plugins/issue-triage.md
docs/plugins/issue-triage.md
internal/pkg/externalplugins/config.go
internal/pkg/externalplugins/issuetriage/issuetriage.go
internal/pkg/externalplugins/issuetriage/issuetriage_test.go

Close issue: #996 
- will not add `needs-cherry-pick-x.y` label to PR if `x.y` is in wont fix versions

feat(externalplugins/issuetriage): support wont fix feature

---

.prow.yaml
configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml

- job: post-tichi-label-sync
- image: gcr.io/k8s-prow/label_sync

ci: fix job's container command after image upgraded

---

configs/prow-dev/cluster/tide_deployment.yaml

- built with https://github.com/ti-community-infra/test-infra/tree/upgrade-tide-with-hacks

fix(deps): bump image ticommunityinfra/tide to v20221207-9225e3a153

---

.github/workflows/gh-pages.yml
.github/workflows/golangci-lint.yml
.github/workflows/preview.yml

Current the gh page action was pending since no agents provided, I think current github has none ubuntu-18 free agents.

ci: fix gh page workflow

---

docs/_sidebar.md
docs/en/_sidebar.md
docs/en/plugins/label-blocker.md
docs/en/workflows/pr-old.md
docs/en/workflows/pr.md
docs/plugins/label-blocker.md
docs/workflows/pr-old.md
docs/workflows/pr.md

Update the PR workflow to builtin `lgtm` + `approve` plugins.

docs: add new workflow documents

---

configs/prow-dev/config/external_plugins_config.yaml
docs/en/plugins/issue-triage.md
docs/plugins/issue-triage.md
internal/pkg/externalplugins/issuetriage/issuetriage.go

This pull request includes several changes to improve the `issue-triage` plugin's functionality and update related documentation. The most important changes include adding the `/retest` command to trigger issue triage checks, modifying regular expressions, and updating documentation for consistency.
Enhancements to `issue-triage` plugin:
* Updated the `checkIssueTriagedRe` regular expression to include the `/retest` command in `issuetriage.go`.
* Modified the `HelpProvider` function to include the `/retest` command in the usage and examples in `issuetriage.go`.
Configuration updates:
* Added the `/retest` command to the `message` field in `ti-community-label-blocker` configuration in `external_plugins_config.yaml`.
* Corrected the `regexp` field formatting in `ti-community-format-checker` …

feat(issuetriage): support fresh the status by `/retest` command
