ti-community-infra/tichi

README.md
=> chore: refine README.md

configs/prow/config/external_plugins_config.yaml
=> config: refine fmt

internal/pkg/externalplugins/respond.go
close https://github.com/tidb-community-bots/ti-community-prow/issues/73
=> fix: add command help link

configs/prow/cluster/branchprotector.yaml, configs/prow/cluster/crier_deployment.yaml, configs/prow/cluster/deck_deployment.yaml, configs/prow/cluster/ghproxy.yaml, configs/prow/cluster/hook_deployment.yaml, configs/prow/cluster/horologium_deployment.yaml, configs/prow/cluster/label_sync.yaml, configs/prow/cluster/needs-rebase_deployment.yaml, configs/prow/cluster/plank_deployment.yaml, configs/prow/cluster/prow_controller_manager_deployment.yaml, configs/prow/cluster/sinker_deployment.yaml, configs/prow/cluster/statusreconciler_deployment.yaml, configs/prow/cluster/tide_deployment.yaml, configs/prow/config/config.yaml
close https://github.com/tidb-community-bots/ti-community-prow/issues/4
=> build: bump version to v20201102-45eeca6478

.prow.yaml, configs/prow/cluster/branchprotector.yaml, configs/prow/cluster/crier_deployment.yaml, configs/prow/cluster/deck_deployment.yaml, configs/prow/cluster/ghproxy.yaml, configs/prow/cluster/hook_deployment.yaml, configs/prow/cluster/horologium_deployment.yaml, configs/prow/cluster/label_sync.yaml, configs/prow/cluster/needs-rebase_deployment.yaml, configs/prow/cluster/plank_deployment.yaml, configs/prow/cluster/prow_controller_manager_deployment.yaml, configs/prow/cluster/sinker_deployment.yaml, configs/prow/cluster/statusreconciler_deployment.yaml, configs/prow/cluster/tide_deployment.yaml, configs/prow/config/config.yaml, configs/prow/config/plugins.yaml, go.mod, go.sum
close https://github.com/tidb-community-bots/ti-community-prow/issues/136
=> build: bump deps version

configs/prow/cluster/ti_community_tars_deployment.yaml, internal/pkg/externalplugins/tars/tars.go
=> fix: refine pull request type

internal/pkg/externalplugins/owners/owners.go, internal/pkg/externalplugins/owners/owners_test.go
close https://github.com/tidb-community-bots/ti-community-prow/issues/156.
/hold
=> fix: only push and admin collaborator can lgtm and merge non sig label PR

configs/prow/cluster/ti_community_autoresponder_deployment.yaml, configs/prow/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow/cluster/ti_community_label_deployment.yaml, configs/prow/cluster/ti_community_lgtm_deployment.yaml, configs/prow/cluster/ti_community_merge_deployment.yaml, configs/prow/cluster/ti_community_owners_deployment.yaml, configs/prow/cluster/ti_community_tars_deployment.yaml
=> build: bump version

configs/prow/config/external_plugins_config.yaml, configs/prow/config/plugins.yaml
enable blunderbuss/tars/needs-rebase for tidb-community-bots org repos
=> config: enable more plugins for tidb-community-bots org repos

docs/src/plugins/label.md, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/label/label.go, internal/pkg/externalplugins/label/label_test.go
=> feat: label support ExcludeLabels

internal/pkg/externalplugins/label.go, internal/pkg/externalplugins/lgtm/lgtm.go, internal/pkg/externalplugins/lgtm/lgtm_test.go, internal/pkg/externalplugins/merge/merge.go, internal/pkg/externalplugins/merge/merge_test.go, internal/pkg/externalplugins/owners/owners.go
=> refactor: move the label and label preifx constants to label.go

cmd/ticommunityautoresponder/main.go, cmd/ticommunityblunderbuss/main.go, cmd/ticommunitylabel/main.go, cmd/ticommunitylgtm/main.go, cmd/ticommunitymerge/main.go, cmd/ticommunityowners/main.go
=> refactor: update default path of the external plugin config file

configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml
=> refactor: update the mount path of external plugins config

cmd/rerere/main.go, internal/pkg/rerere/rerere.go
close https://github.com/tidb-community-bots/ti-community-prow/issues/206
=> fix: refine rerere flags

configs/prow-dev/config/external_plugins_config.yaml, docs/src/plugins/owners.md, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/owners/owners.go, internal/pkg/externalplugins/owners/owners_test.go
=> feat: support setting multiple trusted teams and required LGTM for branches

docs/src/plugins/blunderbuss.md, internal/pkg/externalplugins/blunderbuss/blunderbuss.go, internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/config_test.go
=> feat: add delay time for bluderbuss to wait for sig label to be added

.prow.yaml, configs/prow-dev/.gitignore, configs/prow-dev/Makefile, configs/prow-dev/config/plugins.yaml, configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
=> config: add rustin-bot-periodics.yaml

cmd/ticommunityautoresponder/main.go, internal/pkg/externalplugins/autoresponder/autoresponder.go, internal/pkg/externalplugins/autoresponder/autoresponder_test.go
close https://github.com/ti-community-infra/ti-community-prow/issues/213
part of https://github.com/ti-community-infra/ti-community-prow/issues/212
=> feat: auto responder support all comment events

.github/workflows/web.yml, web/README.md, web/package.json, web/pages/[org]/[repo]/pulls/[num]/owners.module.scss, web/pages/[org]/[repo]/pulls/[num]/owners.tsx, web/pages/api/hello.js, web/pages/index.tsx, web/tsconfig.json, web/types/owners.ts, web/utils/constant.ts, web/utils/request.ts
ref issue: https://github.com/tidb-community-bots/ti-community-prow/issues/166
=> feat: add Owner page

configs/prow-dev/config/external_plugins_config.yaml, configs/prow-dev/config/plugins.yaml, docs/src/plugins/owners.md
Add more configuration items for test-dev
=> config: add more configuration items for test-dev

cmd/chingwei/main.go, deployments/components/chingwei/Dockerfile, experiment/chingwei/chingwei.go
=> feat: add chingwei

configs/prow-dev/config/config.yaml
cc: https://github.com/ti-community-infra/ti-community-prow/issues/255
=> config: add merge_commit_template

docs/plugins/owners.md, internal/pkg/externalplugins/owners/owners.go, internal/pkg/externalplugins/owners/owners_test.go, internal/pkg/externalplugins/owners/types.go
close https://github.com/ti-community-infra/ti-community-prow/issues/257
=> feat: giving permissions to all sig reviewers and committers

internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/config_test.go, internal/pkg/externalplugins/lgtm/lgtm.go, internal/pkg/externalplugins/merge/merge.go, test/testdata/config_test.yaml, test/testdata/config_update.yaml, web/pages/[org]/[repo]/pulls/[num]/owners.tsx
close https://github.com/ti-community-infra/tichi/issues/166
=> feat: use tichi owners page

.prow.yaml, configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml, configs/prow-dev/cluster/tichi_web_deployment.yaml
=> config: bump version from v0.17.4 to v0.17.5

docs/en/plugins/merge.md, docs/plugins/merge.md, internal/pkg/externalplugins/merge/merge.go, internal/pkg/externalplugins/merge/merge_test.go
close https://github.com/ti-community-infra/tichi/issues/253
=> fix: remove merge limit for committer

configs/prow-dev/Makefile, configs/prow-dev/cluster/gcs-secrets.example.yaml, configs/prow-dev/cluster/github-token.example.yaml, configs/prow-dev/cluster/hmac-token.example.yaml
close https://github.com/ti-community-infra/tichi/issues/264
=> chore: add comments for makefile

.goreleaser.yml, deployments/plugins/labelblocker/Dockerfile
=> config: add Dockerfile and releaser config for label blocker

docs/en/_sidebar.md, docs/en/plugins/blunderbuss.md, docs/plugins/blunderbuss.md, go.mod, go.sum, internal/pkg/externalplugins/blunderbuss/blunderbuss.go, internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
close https://github.com/ti-community-infra/tichi/issues/315
part of https://github.com/ti-community-infra/tichi/issues/356
=> feat: blunderbuss support weighted assign

cmd/ticommunityautoresponder/main.go, cmd/ticommunityblunderbuss/main.go, cmd/ticommunitylabel/main.go, cmd/ticommunitylabelblocker/main.go, cmd/ticommunitylgtm/main.go, cmd/ticommunitymerge/main.go, cmd/ticommunitytars/main.go, internal/pkg/externalplugins/event_type.go
add github event type enum for external plugin
=> feat: add event type enum

internal/pkg/externalplugins/tars/tars.go
Need to give GitHub some time to calculate.
=> fix: tars wait a few seconds to give github a chance to calculate PR mergeable status

internal/pkg/externalplugins/tars/tars.go
Still UNKNOWN:
```
{"event-GUID":"ac07dbee-7b37-11eb-8bbd-5a7418a6052d","event-type":"push","level":"info","msg":"Skipped because have conflicting or unknown status: UNKNOWN.","org":"ti-community-infra","plugin":"ti-community-tars","pr":287,"repo":"test-dev","time":"2021-03-02T09:14:26Z"}
{"event-GUID":"ac07dbee-7b37-11eb-8bbd-5a7418a6052d","event-type":"push","level":"info","msg":"Skipped because have conflicting or unknown status: UNKNOWN.","org":"ti-community-infra","plugin":"ti-community-tars","pr":288,"repo":"test-dev","time":"2021-03-02T09:14:26Z"}
```
=> fix: tars wait more time

cmd/ticommunityautoresponder/main.go, cmd/ticommunityblunderbuss/main.go, cmd/ticommunitylabel/main.go, cmd/ticommunitylabelblocker/main.go, cmd/ticommunitylgtm/main.go, cmd/ticommunitymerge/main.go, cmd/ticommunityowners/main.go, cmd/ticommunitytars/main.go, configs/prow-dev/config/external_plugins_config.yaml, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/config_test.go, internal/pkg/externalplugins/plugins.go, test/testdata/config_combine.yaml, test/testdata/config_test.yaml, test/testdata/config_update.yaml
=>  feat: support log level config for external plugin

docs/en/_sidebar.md, docs/en/plugins/lgtm.md, docs/plugins/lgtm.md
part of https://github.com/ti-community-infra/tichi/issues/356
=> docs: add translation for lgtm

docs/en/_sidebar.md, docs/en/plugins/hold.md, docs/en/plugins/require-matching-label.md, docs/en/plugins/wip.md, docs/plugins/hold.md, docs/plugins/require-matching-label.md, docs/plugins/wip.md
part of https://github.com/ti-community-infra/tichi/issues/356
=> docs: add translations to the k8s plugins

.goreleaser.yml, cmd/ticommunitycontribution/main.go, deployments/plugins/contribution/Dockerfile, docs/README.md, docs/_sidebar.md, docs/en/README.md, docs/en/_sidebar.md, docs/en/plugins/contribution.md, docs/plugins/contribution.md, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/config_test.go, internal/pkg/externalplugins/contribution/contribution.go, internal/pkg/externalplugins/contribution/contribution_test.go, internal/pkg/externalplugins/label.go, internal/pkg/externalplugins/label/label_test.go
close https://github.com/ti-community-infra/tichi/issues/391
=> feat: impl contribution

.github/semantic.yml
cc: https://github.com/ti-community-infra/tichi/pull/435
=> chore: add bump to semantic types

internal/pkg/externalplugins/contribution/contribution_test.go, internal/pkg/externalplugins/label.go, internal/pkg/externalplugins/label/label_test.go, internal/pkg/externalplugins/label_test.go
close https://github.com/ti-community-infra/tichi/issues/428
=> refactor: FormatTestLabels support more args

README.md, docs/README.md, docs/_sidebar.md, docs/en/README.md, docs/en/_sidebar.md, docs/en/tools/autobump.md, docs/tools/autobump.md
=> docs: add autobump tool doc

configs/prow-dev/config/config.yaml
=> config: make tide required for test-dev

web/.prettierignore
=> chore: remove unused prettier ignore

.github/semantic.yml
=> chore: remove unused semantic

.prow.yaml, configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml, configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_contribution_deployment.yaml, configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml, configs/prow-dev/cluster/tichi_web_deployment.yaml
=> build: bump all ti plugins version

.prow.yaml, configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml, configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_contribution_deployment.yaml, configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml, configs/prow-dev/cluster/tichi_web_deployment.yaml, internal/pkg/externalplugins/tars/tars.go, internal/pkg/externalplugins/tars/tars_test.go
This field is a preview field and is not currently available.
=>  fix: Revert "fix: Use MergeStateStatus to reduce the use of tars for the GitHub API(#474)"

docs/README.md, docs/_sidebar.md, docs/en/README.md, docs/en/_sidebar.md, docs/en/plugins/release-note.md, docs/plugins/release-note.md
Part of https://github.com/ti-community-infra/tichi/issues/423
```release-note
none
```
=> docs: add release-note docs

docs/en/plugins/contribution.md, docs/plugins/contribution.md
=> clarify the logic of contribution label

configs/prow-dev/cluster/deck_deployment.yaml, configs/prow-dev/cluster/hook_deployment.yaml, configs/prow-dev/cluster/ing_ingress.yaml, configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml, configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_contribution_deployment.yaml, configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml, configs/prow-dev/cluster/tichi_web_deployment.yaml
part of https://github.com/ti-community-infra/configs/issues/6
=> build: support auto https redirect

internal/pkg/externalplugins/cherrypicker/cherrypicker.go
```release-note
cherrypicker try to create all picks and return aggregate error.
```
=> fix: try to create all picks and return aggregate error

internal/pkg/externalplugins/cherrypicker/cherrypicker.go, internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
close https://github.com/ti-community-infra/tichi/issues/458
```release-note
Cherrypicker support multiple calls per comment.
```
=> feat: support multiple calls per comment

go.mod, internal/pkg/externalplugins/cherrypicker/cherrypicker.go
part of https://github.com/ti-community-infra/tichi/issues/396
```release-note
cherrypicker supports pushing conflicts directly.
```
=> feat: cherrypicker supports pushing conflicts directly

internal/pkg/externalplugins/cherrypicker/cherrypicker.go
=> fix: refine git am automatically aborted

internal/pkg/externalplugins/cherrypicker/cherrypicker.go
=> fix: refine git am failed issue

deployments/plugins/cherrypicker/Dockerfile
=> fix: use git 2.30.2 for cherrypicker

deployments/plugins/cherrypicker/Dockerfile
=> fix: refine dockerfile typo

docs/en/plugins/tars.md, docs/plugins/tars.md, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/config_test.go, internal/pkg/externalplugins/tars/tars.go, internal/pkg/externalplugins/tars/tars_test.go
close https://github.com/ti-community-infra/tichi/issues/487
```release-note
add ExcludeLabels configuration for tars.
```
=> feat: add ExcludeLabels configuration for tars

internal/pkg/externalplugins/cherrypicker/cherrypicker.go, internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
close https://github.com/ti-community-infra/tichi/issues/510
```release-note
Cherrypicker support multiple calls per comment.
```
=> feat:  support multiple calls per comment

docs/en/plugins/blunderbuss.md, docs/plugins/blunderbuss.md, internal/pkg/externalplugins/blunderbuss/blunderbuss.go, internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/config_test.go
close https://github.com/ti-community-infra/tichi/issues/486
part of https://github.com/ti-community-infra/tichi/issues/394
```release-note
add include_reviewers for blunderbuss
```
=> feat: add include_reviewers for blunderbuss

configs/prow-dev/cluster/deck_deployment.yaml, configs/prow-dev/cluster/sinker_deployment.yaml
The default value of sinker's configuration was changed, deck I think it's been a bug and forgot to update it.
=> fix: refine the broken components configurations

.github/workflows/release.yml, .goreleaser.yml, .prow.yaml, cmd/ticommunityautoresponder/main.go, cmd/ticommunityblunderbuss/main.go, cmd/ticommunitycherrypicker/main.go, cmd/ticommunitycontribution/main.go, cmd/ticommunitylabel/main.go, cmd/ticommunitylabelblocker/main.go, cmd/ticommunitylgtm/main.go, cmd/ticommunitymerge/main.go, cmd/ticommunityowners/main.go, cmd/ticommunitytars/main.go, go.mod, go.sum, internal/pkg/externalplugins/tars/tars.go
Also upgraded golang to 1.16. otherwise it won't compile.
=> fix: tars stop pass the expectedHeadSha and use the default value

.goreleaser.yml
=> fix: refine broken releaser 

internal/pkg/externalplugins/cherrypicker/cherrypicker.go, internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
close https://github.com/ti-community-infra/tichi/issues/551
When labeled, only the label being added is processed.
=> fix: cherrypicker only processes added label

go.mod, go.sum
ref: https://github.com/ti-community-infra/configs/pull/339 https://github.com/kubernetes/test-infra/pull/22402
=> build: bump test-infra version

.prow.yaml, configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml, configs/prow-dev/cluster/ti_community_contribution_deployment.yaml, configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml, configs/prow-dev/cluster/tichi_web_deployment.yaml
=> build: bump ti plugins version

internal/pkg/externalplugins/autoresponder/autoresponder.go, internal/pkg/externalplugins/label/label.go, internal/pkg/externalplugins/labelblocker/labelblocker.go, internal/pkg/externalplugins/lgtm/lgtm.go, internal/pkg/externalplugins/merge/merge.go, internal/pkg/externalplugins/tars/tars.go
close https://github.com/ti-community-infra/tichi/issues/394
=> refactor: refine plugins help provider

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
close https://github.com/ti-community-infra/tichi/issues/397
=> docs: add CONTRIBUTING.md

docs/en/plugins/assign.md, docs/plugins/assign.md
=> docs: Why can't someone be assigned?

README.md
=> chore: add link to TiDB

configs/prow-dev/config/external_plugins_config.yaml, docs/en/plugins/blunderbuss.md, docs/plugins/blunderbuss.md, test/testdata/config_combine.yaml
=> chore: clean up rustin-bot configs

cmd/ticommunityowners/main.go, configs/prow-dev/config/external_plugins_config.yaml, docs/en/plugins/owners.md, docs/plugins/owners.md, internal/pkg/externalplugins/owners/owners.go, internal/pkg/externalplugins/owners/owners_test.go
close https://github.com/ti-community-infra/tichi/issues/590
=> feat: Adding more granular GitHub permission controls for owners

.github/workflows/golangci-lint.yml, .prow.yaml
=> ci: enable rerere for tichi

docs/en/plugins/cherrypicker.md, docs/plugins/cherrypicker.md, internal/pkg/externalplugins/cherrypicker/cherrypicker.go, internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go, internal/pkg/externalplugins/config.go
=> feat: remove request review feature from cherrypicker

internal/pkg/externalplugins/lgtm/lgtm.go, internal/pkg/externalplugins/lgtm/lgtm_test.go
=> feat: return review notification by update comment

configs/prow-dev/config/config.yaml
This reverts commit 2ea81543f4288ec9c4fbf900193fa2e0ec2661c1.
=> Revert "config: remove the required_approving_review_count"

configs/prow-dev/config/external_plugins_config.yaml
=> config: limit grammar of the associate issue number

docs/en/plugins/lgtm.md, docs/plugins/lgtm.md, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/lgtm/lgtm.go
=> feat: lgtm support ignore the prompt when approval is invalid

docs/en/plugins/cherrypicker.md, docs/plugins/cherrypicker.md, internal/pkg/externalplugins/cherrypicker/cherrypicker.go, internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go, internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/utils/issue_number.go, internal/pkg/externalplugins/utils/issue_number_test.go
=> feat(cherrypicker): support copy issue numbers from squashed commit

configs/prow-dev/config/external_plugins_config.yaml
=> config: enable copy_issue_numbers_from_squashed_commit for test-dev

internal/pkg/externalplugins/formatchecker/formatchecker.go, internal/pkg/externalplugins/formatchecker/formatchecker_test.go
=> feat(formatchecker): regexp rule support template and provide .Org .Repo data

.prow.yaml, configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml, configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml, configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml, configs/prow-dev/cluster/ti_community_contribution_deployment.yaml, configs/prow-dev/cluster/ti_community_format_checker_deployment.yaml, configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml, configs/prow-dev/cluster/ti_community_label_deployment.yaml, configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml, configs/prow-dev/cluster/ti_community_merge_deployment.yaml, configs/prow-dev/cluster/ti_community_owners_deployment.yaml, configs/prow-dev/cluster/ti_community_tars_deployment.yaml, configs/prow-dev/cluster/tichi_web_deployment.yaml, configs/prow-dev/config/external_plugins_config.yaml
=> build: bump ti plugins version from v1.9.3 to v1.9.4

internal/pkg/externalplugins/config.go, internal/pkg/externalplugins/formatchecker/formatchecker.go, internal/pkg/externalplugins/formatchecker/formatchecker_test.go, internal/pkg/externalplugins/issuetriage/issuetriage.go
=> feat(format-checker): add trusted user option

docs/en/plugins/label.md, docs/plugins/label.md
=> docs: update labels docs

.github/workflows/release.yml, .gitignore, .goreleaser.yml
- upgrade goreleaser tool to v1.10.3, yaml should change to pass config checking
- update github action workflow
=> build(goreleaser): upgrade to version `v1.10.3`

configs/prow-dev/cluster/crier_rbac.yaml, configs/prow-dev/cluster/deck_rbac.yaml, configs/prow-dev/cluster/hook_rbac.yaml, configs/prow-dev/cluster/horologium_rbac.yaml, configs/prow-dev/cluster/ing_ingress.yaml, configs/prow-dev/cluster/prow_controller_manager_rbac.yaml, configs/prow-dev/cluster/prowjob_customresourcedefinition.yaml, configs/prow-dev/cluster/sinker_rbac.yaml, configs/prow-dev/cluster/statusreconciler_rbac.yaml, configs/prow-dev/cluster/tide_rbac.yaml
migrate with guide: https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22?_ga=2.123900106.-1597814552.1659254325
=> build(configs/prow-dev): upgrade crd

.goreleaser.yml
main should set to pkg dir instead of main file.
=> ci: fix goreleaseer jobs

internal/pkg/externalplugins/cherrypicker/cherrypicker.go
- add target branch in response comment.
=> feat(cherrypicker): add target branch info in comment when pull request created

cmd/ticommunitycherrypicker/main.go
Fixes #1131
Signed-off-by: wuhuizuo <wuhuizuo@126.com>
=> fix(cmd/ticommunitycherrypicker): fix cherry-pick invite crashed
